// This file is a backward-compat stub. The actual source moved to:
//   src/App.tsx
// Build with Vite: `npm run dev` or `npm run build`.
// Do not edit this file — edit src/App.tsx instead.
export { default } from './src/App'